
- name: template free5gc files
  ansible.builtin.template:
    src: "{{item}}"
    mode: '0777'
    dest: "/opt/{{item}}"
  loop:
  - amfcfg.yaml
  - ausfcfg.yaml
  - docker-compose.yaml
  - n3iwf-ipsec.sh
  - n3iwfcfg.yaml
  - nrfcfg.yaml
  - nssfcfg.yaml
  - pcfcfg.yaml
  - smfcfg.yaml
  - udmcfg.yaml
  - udrcfg.yaml
  - uerouting.yaml
  - webuicfg.yaml

- name: start free5gc control plane
  community.docker.docker_compose_v2:
    project_src: /opt/
    state: present
