# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create incidents directory
  file:
    path: /opt/incidents-repo
    state: directory
    owner: git
    group: git
    mode: 0775

- name: Create postmortems directory
  file:
    path: /opt/incidents-repo/postmortems
    state: directory
    owner: git
    group: git
    mode: 0775

- name: init git repo
  command: sudo -u git git init
  args:
    chdir: /opt/incidents-repo

- name: configure git user name
  command: "sudo -u git git config --global user.name 'Network Agent'"
  args:
    chdir: /opt/incidents-repo

- name: configure git email
  command: "sudo -u git git config --global user.email 'networkagent@example.com'"
  args:
    chdir: /opt/incidents-repo

###############################################
# Master Branch
###############################################
- name: checkout master branch
  command: sudo -u git git checkout -B master
  args:
    chdir: /opt/incidents-repo

- name: push incidents files to master
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/incidents-repo/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
   - operating_procedure.md
   - Readme.md

- name: push incidents files to master
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/opt/incidents-repo/postmortems/{{item}}"
    owner: git
    group: git
    mode: '0644'
  loop:
   - postmortem1.md

- name: add to master branch in incidents repo
  command: sudo -u git git add .
  args:
    chdir: /opt/incidents-repo

- name: initial commit 
  command: sudo -u git git commit -m "initial commit"
  args:
    chdir: /opt/incidents-repo

- name: add remote repo
  command: sudo -u git git remote add origin https://{{ lookup('env', 'WEBAPPS_LOGIN') }}:{{ lookup('env', 'WEBAPPS_PWD') }}@{{external_ip_address}}:3000/{{ lookup('env', 'WEBAPPS_LOGIN') }}/incidents.git
  args:
    chdir: /opt/incidents-repo

- name: push to repo
  command: sudo -u git git -c http.sslVerify=false push -u origin master
  args:
    chdir: /opt/incidents-repo
