version: '3.8'

services:
  upf:
    container_name: upf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/upf:latest
    command: "./upf -c ./config/upfcfg.yaml"
    volumes:
      - /opt/upfcfg.yaml:/free5gc/config/upfcfg.yaml
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      GIN_MODE: release
    labels:
      free5gc_name: upf


