---
apiVersion: google.dev/v1
kind: TrafficTest
metadata:
  name: simple-test
  namespace: default
spec:
  source_devices:
    - dev1  # First source device
  destination_device: devhub
  protocol: TCP
  port_mode: auto # Self allocated by the traffic test operator
  duration: 14400  # 240 minutes
  bandwidth: 5Mbps  # Each source sends 5Mbps
  pattern_type: constant
  concurrent_users: 10
