# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: controlplanes.google.dev
  labels:
    type: networkservices
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: ControlPlane
    plural: controlplanes
    singular: controlplane
    shortNames:
      - cp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            This network service is a 5G control plane. This control plane requires a User Plane Function network service (of kind UserPlaneFunction) 
            to be up and runing and its details provided below.

            Also a Data Network network service (of kind DataNetwork) needs to be running and details provided below. 
          properties:
            spec:
              type: object
              properties:
                network:
                  type: object
                  description: the GCP VPC network to attach the control plane to 
                  properties:
                    name: 
                      type: string
                      description: VPC network name
                upf:
                  description: The UserPlaneFunction network service to the connect control plane to
                  type: object
                  properties:
                    name:
                      description: name of the User Plane Function (upf)
                      type: string
                dnn:
                  description: The DataNetwork network service to connect the ControlPlane network service to
                  type: object
                  properties:
                    name:
                      description: name of the Data Network (dnn)
                      type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true