# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: uetests.google.dev
  labels:
    type: networktest
spec:
  scope: Namespaced
  group: google.dev
  names:
    kind: UETest
    plural: uetests
    singular: uetest
    shortNames:
      - uetest
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: |
            This test simulates mobile user traffic by logging into a UERanSim service and running web traffic to the Data Network.
          type: object
          properties:
            spec:
              type: object
              properties:
                ueransim: 
                  description: the name of the UERanSim network service virtual machine to log into and run traffic
                  type: object
                  properties:
                    name:
                      description: name of the UERanSim instance
                      type: string
                datanetwork: 
                  description: the name of the DataNetwork network service to send traffic to
                  type: object
                  properties:
                    name:
                      description: name of the DataNetwork instance
                      type: string
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true