# Copyright 2024-2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: copy UPF configuration
  ansible.builtin.template: 
    src: "{{item}}"
    dest: "/opt/{{item}}"
    mode: '0777'
  loop:
  - upfcfg.yaml
  - upf-iptables.sh
  - docker-compose.yaml

# run the iptables script
- name: run the iptables script
  become: True
  raw: "/opt/upf-iptables.sh"

- name: start free5gc upf
  community.docker.docker_compose_v2:
    project_src: /opt/
    state: present
