version: '3.8'

services:
  db:
    container_name: mongodb
    image: mongo
    command: mongod --port 27017
    volumes:
      - dbdata:/data/db
    network_mode: host
    labels:
      free5gc_name: mongodb

  free5gc-nrf:
    container_name: nrf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/nrf:latest
    command: ./nrf -c ./config/nrfcfg.yaml
    volumes:
      - /opt/nrfcfg.yaml:/free5gc/config/nrfcfg.yaml
    environment:
      DB_URI: mongodb://127.0.0.1/free5gc
      GIN_MODE: release
    network_mode: host
    depends_on:
      - db
    labels:
      free5gc_name: nrf

  free5gc-amf:
    container_name: amf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/amf:latest
    command: ./amf -c ./config/amfcfg.yaml
    volumes:
      - /opt/amfcfg.yaml:/free5gc/config/amfcfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - free5gc-nrf
    labels:
      free5gc_name: amf

  free5gc-ausf:
    container_name: ausf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/ausf:latest
    command: ./ausf -c ./config/ausfcfg.yaml
    volumes:
      - /opt/ausfcfg.yaml:/free5gc/config/ausfcfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - free5gc-nrf
    labels:
      free5gc_name: ausf

  free5gc-nssf:
    container_name: nssf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/nssf:latest
    command: ./nssf -c ./config/nssfcfg.yaml
    volumes:
      - /opt/nssfcfg.yaml:/free5gc/config/nssfcfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - free5gc-nrf
    labels:
      free5gc_name: nssf

  free5gc-pcf:
    container_name: pcf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/pcf:latest
    command: ./pcf -c ./config/pcfcfg.yaml
    volumes:
      - /opt/pcfcfg.yaml:/free5gc/config/pcfcfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - free5gc-nrf
    labels:
      free5gc_name: pcf

  free5gc-smf:
    container_name: smf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/smf:latest
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    volumes:
      - /opt/smfcfg.yaml:/free5gc/config/smfcfg.yaml
      - /opt/uerouting.yaml:/free5gc/config/uerouting.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - free5gc-nrf
    labels:
      free5gc_name: smf

  free5gc-udm:
    container_name: udm
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/udm:latest
    command: ./udm -c ./config/udmcfg.yaml
    volumes:
      - /opt/udmcfg.yaml:/free5gc/config/udmcfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - db
      - free5gc-nrf
    labels:
      free5gc_name: udm

  free5gc-udr:
    container_name: udr
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/udr:latest
    command: ./udr -c ./config/udrcfg.yaml
    volumes:
      - /opt/udrcfg.yaml:/free5gc/config/udrcfg.yaml
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    network_mode: host
    depends_on:
      - db
      - free5gc-nrf
    labels:
      free5gc_name: udr

  free5gc-n3iwf:
    container_name: n3iwf
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/n3iwf:latest
    command: sh -c "./n3iwf-ipsec.sh && ./n3iwf -c ./config/n3iwfcfg.yaml"
    volumes:
      - /opt/n3iwfcfg.yaml:/free5gc/config/n3iwfcfg.yaml
      - /opt/n3iwf-ipsec.sh:/free5gc/n3iwf-ipsec.sh
    environment:
      GIN_MODE: release
    cap_add:
      - NET_ADMIN
    network_mode: host
    depends_on:
      - free5gc-amf
      - free5gc-smf
    labels:
      free5gc_name: n3iwf

  free5gc-webui:
    container_name: webui
    image: {{GOOGLE_REGION}}-docker.pkg.dev/{{GOOGLE_PROJECT}}/networkagent/webconsole:latest
    command: ./webui -c ./config/webuicfg.yaml
    volumes:
      - /opt/webuicfg.yaml:/free5gc/config/webuicfg.yaml
    environment:
      GIN_MODE: release
    network_mode: host
    depends_on:
      - db
    labels:
      free5gc_name: webui


volumes:
  dbdata:
